using System.Text;
using System.Text.Json;

namespace AgentGenCli.Cli.Scaffolding;

internal static class AgentDocsGenerator
{
    private const string AgentsDirectoryName = ".agents";
    private const string StateFileName = "state.md";
    private const int RecentCommandLimit = 10;

    public static void ScaffoldInitial(
        string root,
        TemplateTokens tokens,
        bool hasBackend,
        bool hasFlutter
    )
    {
        TemplateEngine.CopyFile("AGENTS.md.template", Path.Combine(root, "AGENTS.md"), tokens);

        var agentsDir = Path.Combine(root, AgentsDirectoryName);
        Directory.CreateDirectory(agentsDir);

        CopyAgentsTemplate("README.md.template", Path.Combine(agentsDir, "README.md"), tokens);
        CopyAgentsTemplate("overview.md.template", Path.Combine(agentsDir, "overview.md"), tokens);
        CopyAgentsTemplate("cli.md.template", Path.Combine(agentsDir, "cli.md"), tokens);

        if (hasBackend)
        {
            CopyAgentsTemplate("backend.md.template", Path.Combine(agentsDir, "backend.md"), tokens);
        }

        if (hasFlutter)
        {
            CopyAgentsTemplate("frontend.md.template", Path.Combine(agentsDir, "frontend.md"), tokens);
        }

        RefreshState(root);
    }

    public static void RefreshState(string root)
    {
        var manifest = ProjectManifest.Load(root);
        var statePath = Path.Combine(root, AgentsDirectoryName, StateFileName);
        Directory.CreateDirectory(Path.GetDirectoryName(statePath)!);
        File.WriteAllText(statePath, BuildStateMarkdown(manifest), Encoding.UTF8);
    }

    internal static string BuildStateMarkdown(ProjectManifestDocument manifest)
    {
        var (backend, frontend) = GetInitStacks(manifest);
        var hasBackend = string.Equals(backend, "dotnet", StringComparison.OrdinalIgnoreCase);
        var hasFlutter = string.Equals(frontend, "flutter", StringComparison.OrdinalIgnoreCase);

        var builder = new StringBuilder();
        builder.AppendLine("<!-- generated by agentGenCli; do not edit -->");
        builder.AppendLine();
        builder.AppendLine("# Project state");
        builder.AppendLine();
        builder.AppendLine($"- Project: {manifest.ProjectName}");
        builder.AppendLine($"- Initialized: {manifest.InitializedAt:yyyy-MM-dd}");
        builder.AppendLine($"- Backend: {backend ?? "unknown"}");
        builder.AppendLine($"- Frontend: {frontend ?? "unknown"}");
        builder.AppendLine();
        builder.AppendLine("## Init modules");
        builder.AppendLine();
        builder.AppendLine($"- Email (SendGrid): {FormatBool(manifest.EmailInitialized)}");
        builder.AppendLine($"- Auth (Users + JWT): {FormatBool(manifest.AuthInitialized)}");
        builder.AppendLine();
        builder.AppendLine("## Enabled stacks");
        builder.AppendLine();

        if (hasBackend)
        {
            builder.AppendLine("- Backend guide: `.agents/backend.md`");
        }
        else
        {
            builder.AppendLine("- Backend guide: *(not scaffolded — backend is not dotnet)*");
        }

        if (hasFlutter)
        {
            builder.AppendLine("- Frontend guide: `.agents/frontend.md`");
        }
        else
        {
            builder.AppendLine("- Frontend guide: *(not scaffolded — frontend is not flutter)*");
        }

        if (hasBackend)
        {
            AppendBackendFeatures(builder, manifest);
        }

        if (hasFlutter)
        {
            AppendFrontendFeatures(builder, manifest);
        }

        AppendRecentCommands(builder, manifest);
        return builder.ToString();
    }

    private static void CopyAgentsTemplate(
        string templateFileName,
        string destinationPath,
        TemplateTokens tokens
    )
    {
        TemplateEngine.CopyFile(
            Path.Combine(AgentsDirectoryName, templateFileName),
            destinationPath,
            tokens
        );
    }

    private static (string? Backend, string? Frontend) GetInitStacks(ProjectManifestDocument manifest)
    {
        var initCommand = manifest.Commands.LastOrDefault(static entry =>
            string.Equals(entry.Command, "init project", StringComparison.Ordinal)
        );

        if (initCommand?.Args == null)
        {
            return (null, null);
        }

        string? backend = null;
        string? frontend = null;

        if (initCommand.Args.TryGetValue("backend", out var backendElement))
        {
            backend = backendElement.GetString();
        }

        if (initCommand.Args.TryGetValue("frontend", out var frontendElement))
        {
            frontend = frontendElement.GetString();
        }

        return (backend, frontend);
    }

    private static void AppendBackendFeatures(StringBuilder builder, ProjectManifestDocument manifest)
    {
        builder.AppendLine();
        builder.AppendLine("## Backend features");
        builder.AppendLine();

        var features = CollectBackendFeatures(manifest);
        if (features.Count == 0)
        {
            builder.AppendLine("*(none yet — use `agentGenCli new backend-feature`)*");
            return;
        }

        builder.AppendLine("| Feature | Database | API | CRUD |");
        builder.AppendLine("|---------|----------|-----|------|");

        foreach (var feature in features.Values.OrderBy(static f => f.Name, StringComparer.OrdinalIgnoreCase))
        {
            var crud = string.IsNullOrEmpty(feature.Crud) ? "—" : feature.Crud;
            builder.AppendLine(
                $"| {feature.Name} | {FormatBool(feature.WithDatabase)} | {FormatBool(feature.WithApi)} | {crud} |"
            );
        }
    }

    private static void AppendFrontendFeatures(StringBuilder builder, ProjectManifestDocument manifest)
    {
        builder.AppendLine();
        builder.AppendLine("## Frontend features");
        builder.AppendLine();

        var features = CollectFrontendFeatures(manifest);
        if (features.Count == 0)
        {
            builder.AppendLine("*(none yet — use `agentGenCli new frontend-feature`)*");
            return;
        }

        builder.AppendLine("| Feature | API wired |");
        builder.AppendLine("|---------|-----------|");

        foreach (var feature in features.Values.OrderBy(static f => f.Name, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine($"| {feature.Name} | {FormatBool(feature.WithApi)} |");
        }
    }

    private static void AppendRecentCommands(StringBuilder builder, ProjectManifestDocument manifest)
    {
        builder.AppendLine();
        builder.AppendLine("## Recent agentGenCli commands");
        builder.AppendLine();

        if (manifest.Commands.Count == 0)
        {
            builder.AppendLine("*(none recorded)*");
            return;
        }

        foreach (var entry in manifest.Commands.TakeLast(RecentCommandLimit))
        {
            var argsSummary = FormatCommandArgs(entry.Args);
            builder.AppendLine(
                string.IsNullOrEmpty(argsSummary)
                    ? $"- `{entry.Command}` ({entry.At:yyyy-MM-dd HH:mm} UTC)"
                    : $"- `{entry.Command}` {argsSummary} ({entry.At:yyyy-MM-dd HH:mm} UTC)"
            );
        }
    }

    private static Dictionary<string, BackendFeatureState> CollectBackendFeatures(
        ProjectManifestDocument manifest
    )
    {
        var features = new Dictionary<string, BackendFeatureState>(StringComparer.OrdinalIgnoreCase);

        foreach (var entry in manifest.Commands.Where(static c =>
            string.Equals(c.Command, "new backend-feature", StringComparison.Ordinal)))
        {
            if (entry.Args == null || !entry.Args.TryGetValue("feature", out var featureElement))
            {
                continue;
            }

            var folderName = featureElement.GetString();
            if (string.IsNullOrWhiteSpace(folderName))
            {
                continue;
            }

            var pascalName = ToPascalFromFolder(folderName);
            features[pascalName] = new BackendFeatureState
            {
                Name = pascalName,
                WithDatabase = GetBoolArg(entry.Args, "withDatabase"),
                WithApi = GetBoolArg(entry.Args, "withApi"),
                Crud = GetStringArg(entry.Args, "crud"),
            };
        }

        foreach (var featureName in manifest.Features)
        {
            features.TryAdd(
                featureName,
                new BackendFeatureState
                {
                    Name = featureName,
                    WithDatabase = false,
                    WithApi = false,
                    Crud = string.Empty,
                }
            );
        }

        return features;
    }

    private static Dictionary<string, FrontendFeatureState> CollectFrontendFeatures(
        ProjectManifestDocument manifest
    )
    {
        var features = new Dictionary<string, FrontendFeatureState>(StringComparer.OrdinalIgnoreCase);

        foreach (var entry in manifest.Commands.Where(static c =>
            string.Equals(c.Command, "new frontend-feature", StringComparison.Ordinal)))
        {
            if (entry.Args == null || !entry.Args.TryGetValue("feature", out var featureElement))
            {
                continue;
            }

            var folderName = featureElement.GetString();
            if (string.IsNullOrWhiteSpace(folderName))
            {
                continue;
            }

            var pascalName = ToPascalFromFolder(folderName);
            features[pascalName] = new FrontendFeatureState
            {
                Name = pascalName,
                WithApi = GetBoolArg(entry.Args, "withApi"),
            };
        }

        foreach (var featureName in manifest.FrontendFeatures)
        {
            features.TryAdd(
                featureName,
                new FrontendFeatureState { Name = featureName, WithApi = false }
            );
        }

        return features;
    }

    private static string FormatCommandArgs(Dictionary<string, JsonElement>? args)
    {
        if (args == null || args.Count == 0)
        {
            return string.Empty;
        }

        var parts = args
            .OrderBy(static pair => pair.Key, StringComparer.Ordinal)
            .Select(static pair => $"{pair.Key}={FormatJsonElement(pair.Value)}");

        return $"({string.Join(", ", parts)})";
    }

    private static string FormatJsonElement(JsonElement element) =>
        element.ValueKind switch
        {
            JsonValueKind.String => element.GetString() ?? string.Empty,
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            JsonValueKind.Number => element.ToString(),
            _ => element.ToString(),
        };

    private static bool GetBoolArg(Dictionary<string, JsonElement> args, string key) =>
        args.TryGetValue(key, out var element) && element.ValueKind == JsonValueKind.True;

    private static string GetStringArg(Dictionary<string, JsonElement> args, string key) =>
        args.TryGetValue(key, out var element) ? element.GetString() ?? string.Empty : string.Empty;

    private static string FormatBool(bool value) => value ? "yes" : "no";

    private static string ToPascalFromFolder(string folderName)
    {
        if (string.IsNullOrWhiteSpace(folderName))
        {
            return folderName;
        }

        var segments = FeatureNameNormalizer.SplitIntoSegments(folderName);
        return FeatureNameNormalizer.ToPascalName(segments);
    }

    private sealed class BackendFeatureState
    {
        public required string Name { get; init; }

        public bool WithDatabase { get; init; }

        public bool WithApi { get; init; }

        public string Crud { get; init; } = string.Empty;
    }

    private sealed class FrontendFeatureState
    {
        public required string Name { get; init; }

        public bool WithApi { get; init; }
    }
}
