using System.Text.Json;
using AgentGenCli.Cli.Scaffolding;
using Xunit;

namespace AgentGenCli.Cli.Tests;

public class AgentDocsGeneratorTests
{
    [Fact]
    public void BuildStateMarkdown_IncludesBackendAndFrontendStacks()
    {
        var manifest = CreateManifest(
            backend: "dotnet",
            frontend: "flutter",
            backendFeatures: ["Orders"],
            frontendFeatures: ["Home"]
        );

        AddBackendFeatureCommand(manifest, "orders", withDatabase: true, withApi: true, crud: "CRUD");
        AddFrontendFeatureCommand(manifest, "home", withApi: false);

        var markdown = AgentDocsGenerator.BuildStateMarkdown(manifest);

        Assert.Contains("- Backend: dotnet", markdown);
        Assert.Contains("- Frontend: flutter", markdown);
        Assert.Contains("`.agents/backend.md`", markdown);
        Assert.Contains("`.agents/frontend.md`", markdown);
        Assert.Contains("## Backend features", markdown);
        Assert.Contains("| Orders | yes | yes | CRUD |", markdown);
        Assert.Contains("## Frontend features", markdown);
        Assert.Contains("| Home | no |", markdown);
    }

    [Fact]
    public void BuildStateMarkdown_OmitsFeatureSectionsWhenStackDisabled()
    {
        var manifest = CreateManifest(backend: "none", frontend: "none");

        var markdown = AgentDocsGenerator.BuildStateMarkdown(manifest);

        Assert.Contains("*(not scaffolded — backend is not dotnet)*", markdown);
        Assert.Contains("*(not scaffolded — frontend is not flutter)*", markdown);
        Assert.DoesNotContain("## Backend features", markdown);
        Assert.DoesNotContain("## Frontend features", markdown);
    }

    [Fact]
    public void ScaffoldInitial_CopiesBackendOnlyWhenHasBackend()
    {
        using var root = new TempProjectRoot();
        SaveInitManifest(root.RootPath, backend: "dotnet", frontend: "none");

        AgentDocsGenerator.ScaffoldInitial(
            root.RootPath,
            new TemplateTokens { ProjectName = "TestApp" },
            hasBackend: true,
            hasFlutter: false
        );

        Assert.True(File.Exists(Path.Combine(root.RootPath, "AGENTS.md")));
        Assert.True(File.Exists(Path.Combine(root.RootPath, ".agents", "README.md")));
        Assert.True(File.Exists(Path.Combine(root.RootPath, ".agents", "backend.md")));
        Assert.False(File.Exists(Path.Combine(root.RootPath, ".agents", "frontend.md")));
        Assert.Contains("TestApp", File.ReadAllText(Path.Combine(root.RootPath, ".agents", "backend.md")));
    }

    [Fact]
    public void ScaffoldInitial_CopiesBothStackGuidesWhenEnabled()
    {
        using var root = new TempProjectRoot();
        SaveInitManifest(root.RootPath, backend: "dotnet", frontend: "flutter");

        AgentDocsGenerator.ScaffoldInitial(
            root.RootPath,
            new TemplateTokens { ProjectName = "TestApp" },
            hasBackend: true,
            hasFlutter: true
        );

        Assert.True(File.Exists(Path.Combine(root.RootPath, ".agents", "backend.md")));
        Assert.True(File.Exists(Path.Combine(root.RootPath, ".agents", "frontend.md")));
        Assert.Contains("testapp", File.ReadAllText(Path.Combine(root.RootPath, ".agents", "frontend.md")));
    }

    [Fact]
    public void ScaffoldInitial_SkipsBackendGuideWhenHasBackendFalse()
    {
        using var root = new TempProjectRoot();
        SaveInitManifest(root.RootPath, backend: "none", frontend: "flutter");

        AgentDocsGenerator.ScaffoldInitial(
            root.RootPath,
            new TemplateTokens { ProjectName = "TestApp" },
            hasBackend: false,
            hasFlutter: true
        );

        Assert.False(File.Exists(Path.Combine(root.RootPath, ".agents", "backend.md")));
        Assert.True(File.Exists(Path.Combine(root.RootPath, ".agents", "frontend.md")));
    }

    [Fact]
    public void RefreshState_WritesStateFromManifest()
    {
        using var root = new TempProjectRoot();
        var manifest = CreateManifest(backend: "dotnet", frontend: "none");
        ProjectManifest.Save(root.RootPath, manifest);

        AgentDocsGenerator.RefreshState(root.RootPath);

        var state = File.ReadAllText(Path.Combine(root.RootPath, ".agents", "state.md"));
        Assert.StartsWith("<!-- generated by agentGenCli; do not edit -->", state);
        Assert.Contains("- Backend: dotnet", state);
        Assert.Contains("- Frontend: none", state);
    }

    private static void SaveInitManifest(string rootPath, string backend, string frontend)
    {
        var manifest = CreateManifest(backend, frontend);
        ProjectManifest.Save(rootPath, manifest);
    }

    private static ProjectManifestDocument CreateManifest(
        string backend,
        string frontend,
        IEnumerable<string>? backendFeatures = null,
        IEnumerable<string>? frontendFeatures = null
    )
    {
        return new ProjectManifestDocument
        {
            ProjectName = "TestApp",
            InitializedAt = new DateTimeOffset(2026, 6, 6, 12, 0, 0, TimeSpan.Zero),
            Features = backendFeatures?.ToList() ?? [],
            FrontendFeatures = frontendFeatures?.ToList() ?? [],
            Commands =
            [
                new ManifestCommandEntry
                {
                    Command = "init project",
                    At = new DateTimeOffset(2026, 6, 6, 12, 0, 0, TimeSpan.Zero),
                    Args = new Dictionary<string, JsonElement>
                    {
                        ["backend"] = JsonSerializer.SerializeToElement(backend),
                        ["frontend"] = JsonSerializer.SerializeToElement(frontend),
                    },
                },
            ],
        };
    }

    private static void AddBackendFeatureCommand(
        ProjectManifestDocument manifest,
        string feature,
        bool withDatabase,
        bool withApi,
        string crud
    )
    {
        manifest.Commands.Add(
            new ManifestCommandEntry
            {
                Command = "new backend-feature",
                Args = new Dictionary<string, JsonElement>
                {
                    ["feature"] = JsonSerializer.SerializeToElement(feature),
                    ["withDatabase"] = JsonSerializer.SerializeToElement(withDatabase),
                    ["withApi"] = JsonSerializer.SerializeToElement(withApi),
                    ["crud"] = JsonSerializer.SerializeToElement(crud),
                },
            }
        );
    }

    private static void AddFrontendFeatureCommand(
        ProjectManifestDocument manifest,
        string feature,
        bool withApi
    )
    {
        manifest.Commands.Add(
            new ManifestCommandEntry
            {
                Command = "new frontend-feature",
                Args = new Dictionary<string, JsonElement>
                {
                    ["feature"] = JsonSerializer.SerializeToElement(feature),
                    ["withApi"] = JsonSerializer.SerializeToElement(withApi),
                },
            }
        );
    }

    private sealed class TempProjectRoot : IDisposable
    {
        public TempProjectRoot()
        {
            RootPath = Path.Combine(Path.GetTempPath(), "agentGenCli-tests-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(RootPath);
        }

        public string RootPath { get; }

        public void Dispose()
        {
            if (Directory.Exists(RootPath))
            {
                Directory.Delete(RootPath, recursive: true);
            }
        }
    }
}
